micronaut:
  application:
    name: sakuga-rule-engine
  metrics:
    enabled: true
  otel:
    enabled: false
otel:
  logs:
    exporter: otlp, logging
  metrics:
    exporter: otlp, logging
  traces:
    exporter: otlp, logging
  exclusions:
    - /health
otel.exporter.otlp.endpoint: http://localhost:4317

endpoints:
  all:
    port: ${MANAGEMENT_PORT:8085}
